version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=libraryuser
      - DB_PASSWORD=librarypassword
      - DB_DATABASE=librarydb
      - PORT=3000
      - LOG_LEVEL=debug
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: